### ISSUE TITLE
adding rules broken 

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-livetest-chrome-extension#57]
whenever I now edit a default rule, after the edit the default rule vanishes - and the custom rules get forgotten

**Comment by franzenzenhofer** [comment]
hi, could recreate the 

A) "custom rules deleted with default rules update" issue

but not the B) "default rules vanishes after update" issue (but it was there....)


ad A)

create a blank default rule (no text in file)
![image](https://cloud.githubusercontent.com/assets/323190/24141403/9f4905fc-0e23-11e7-90fd-eaa5894c2917.png)

add some custom rules

![image](https://cloud.githubusercontent.com/assets/323190/24141411/a5b18824-0e23-11e7-8105-525c676b5026.png)


update default rule (as some acutal JS) 

-> custom rules are gone
![image](https://cloud.githubusercontent.com/assets/323190/24141445/bd1dff42-0e23-11e7-80eb-4b11cb47e5eb.png)



ad B) could not repleciate but please investigate


MVP critical bug

**Comment by franzenzenhofer** [comment]
hmmm, i just created this default rule
and whatever I do now (even a blank install) this rule does not show up in the setting panel (and does not get executed)
https://github.com/franzenzenhofer/f19n-livetest-chrome-extension/blob/master/src/public/default-rules/static-idle-head-title-compare.js

**Comment by neuling** [comment]
oh noe. will look into it now.

**Comment by neuling** [comment]
removing custom rules on default-rules changes is fixed.

**Comment by neuling** [comment]
the other problem (not being able to add new rules) should also be fixed. we it the quota on the storage. i added the permissions for "unlimitedStorage" to the manifest.

**Comment by franzenzenhofer** [comment]
hi @neuling thx

but deinstalled extension
built the extension again
quit the browser
started the browser again
added extension again
https://github.com/franzenzenhofer/f19n-livetest-chrome-extension/blob/master/src/public/default-rules/static-idle-head-title-compare.js still does not show up?

**Comment by neuling** [comment]
hmm. strange. will check it again and fix it asap.

**Comment by neuling** [comment]
sorry @franzenzenhofer. i found two additional bugs. should finally be fixed now. hopefully. let me know if everything works.
